spring.application.name=ticket-booking-system
spring.datasource.url = jdbc:postgresql://localhost:5432/tickethub
spring.datasource.username=postgres
spring.datasource.password=270504
spring.security.user.name=admin
spring.security.user.password=123456
spring.jpa.hibernate.ddl-auto=update
